services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/var/www/app
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://symfony:symfony@db:5432/postgres

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: symfony
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db

volumes:
  postgres_data: